{
    "data": {
        "version": "2026-04-20 001",
        "arUpiInputUtrSwitch": false,
        "arbApiUrl": [
            "https://apiweb.asjoby.com"
        ],
        "isShowAppDownloadUp": false,
        "isShowAppDownloadDown": true,
        "isShowRewardCenter": true,
        "isShowLotteryDragon": true,
        "isSplitLocalEWallet": true,
        "jackportMaxReswadAmount": 355.00,
        "projectName": "veergame",
        "projectLogo": "https://ossimg.veergamepay.com/veergame/other/h5setting_202608291515262umj.png",
        "languages": "en|hd|ta|te",
        "webIco": "https://ossimg.veergamepay.com/veergame/other/h5setting_20260829151538gix9.png",
        "headLogo": "https://ossimg.veergamepay.com/veergame/other/h5setting_20260829151532fqt9.png",
        "dollarSign": "₹",
        "upperOrLower": "0",
        "defaultCurrentLanguage": "en",
        "registerMobile": "1",
        "registerEmail": "0",
        "areaPhoneLenList": [
            {
                "area": "+91",
                "len": "10"
            }
        ],
        "registerSms": "0",
        "isOpenLoginChangeLanguage": "1",
        "rewardValidityTime": 1,
        "electronicWinRateExternalLink": "",
        "electronicWinRateImgUrl": "",
        "isShowElectronicWinRateExternalLink": false,
        "isShowAppHandCodeWashingSwitch": true,
        "isShowHotGameWinOdds": true,
        "ossUrl": "https://ossimg.veergamepay.com",
        "bigTurntableLink": "",
        "bigTurntableImgUrl": "",
        "telegramExternalLink": "https://t.me/veergame",
        "telegramImgUrl": "",
        "isOpenActivityAward": true,
        "isOpenTurntable": true,
        "isPartnerReward": true,
        "isSelfCustomerService": true,
        "webSiteUrl": "https://www.veergame44.com",
        "isOpenFacebookEvent": false,
        "firstDepositRewardCodeAmount": "1",
        "isOpenRegisterPhoneFirstZeroSwitch": false,
        "eventRegionConfigList": null,
        "isOpenAdjustEvent": false,
        "firebaseConfig": null,
        "isOpenArLottery": false,
        "isSwitchSaasBalance": false,
        "isV3Mode": true,
        "isOpenInvitedWheel": true,
        "invitedWheelTotalPrizeAmount": 500.0,
        "invitedWheelImgUrl": "https://ossimg.veergamepay.com/veergame/tab/wheel.png",
        "isOpenDownAppRewardSwitch": false,
        "isShowDownAppBonusAmountSwitch": false,
        "downAppBonusAmount": 0.0,
        "downAppRechargeAmount": 0.0,
        "needKycValidIsOpen": false,
        "needFastKycValidIsOpen": false,
        "lotteryDragonIcon": null,
        "bonusCenterImgUrl": "",
        "isShowBonusCenterExternalLink": true,
        "isOpenBrowserConsoleDebug": true,
        "homeBigTurntableSwitch": true,
        "homeBigTurntableLink": "",
        "homeBigTurntableImgUrl": "https://ossimg.veergamepay.com/veergame/vendorlogo/vendorlogo_20260904152718kiy3.png",
        "jgConfig": {
            "webConfig": null,
            "appConfig": null
        },
        "lastestAppVersionInfo": null
    },
    "code": 0,
    "msg": "Succeed",
    "msgCode": 0,
    "traceId": "",
    "serviceNowTime": "2026-09-13 01:59:38"
}