{
    "data": {
        "needPopupFirstRecharge": true,
        "isExistGrandAward": false,
        "children_Lv_RebateAmount_Yesterday": 0.00,
        "returnAwards": 0.0,
        "returnNewRechargeAwards": null,
        "isARPay": true,
        "isRSNPay": false,
        "isLandingPageEnabled": false,
        "landingPageUrl": null,
        "isFinancePromptTextEnabled": false,
        "financePromptText": null,
        "isAppDownloadPromptTextEnabled": false,
        "appDownloadPromptText": null,
        "isAppForcedDownloadEnabled": false,
        "appForcedDownloadUrl": null,
        "downAppRewardBonusAmount": 0.0,
        "registerGiftAmount": 0.0,
        "activityRedDot": {
            "activityAwardCount": 0,
            "invitationBonusCount": 0,
            "bettingRebateCount": 0,
            "superJackpotCount": 0,
            "firstGiftCount": 0,
            "invitedWheelCount": 1,
            "attendanceBonusCount": 0,
            "totalCount": 1,
            "newbieGiftPackCount": 0
        },
        "isTaskState": "1",
        "isOpenJackpotReward": "1",
        "isOpenWashCode": "1",
        "unJackpotCount": 0,
        "isOpenActivityAward": "0",
        "unWeeklyAwardCount": 0,
        "isFinishUserGuidelines": false,
        "isFirstUserDayRequest": true,
        "isOpenChampion": "0",
        "newbieGiftPackCount": 0,
        "newMemberGiftPackageSwitch": "0",
        "todayRewards": 0.0,
        "totalRewards": 0.0
    },
    "code": 0,
    "msg": "Succeed",
    "msgCode": 0,
    "traceId": "",
    "serviceNowTime": "2026-09-14 02:27:51"
}