<?php
define('VA_ADMIN',true);require __DIR__.'/lib/bootstrap.php';$a=va_auth();
$page=va_input('page',$_GET);if($page==='')$page='dashboard';
$catalog=va_catalog();$titles=['dashboard'=>'Overview','checks'=>'Integration checks','security'=>'Admin security','user'=>'User profile'];
if(!isset($catalog[$page])&&!isset($titles[$page]))va_fail(404,'Page not found.');
// Complete reads before emitting the document: DB errors cannot leave half-rendered success pages.
$data=null;$checks=null;$u=null;
if(isset($catalog[$page]))$data=va_page_data($page);
if(in_array($page,['checks','dashboard'],true))$checks=va_checks();
if($page==='user') {
    $id=filter_var(va_input('id',$_GET),FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>2147483647]]);
    if(!$id || !($u=va_user($id)))va_fail(404,'User not found or user schema incompatible.');
}
$counts=[];
if($page==='dashboard')foreach(['users','wallets','deposits','withdrawals'] as $key)$counts[$key]=va_count($catalog[$key]['table']);
va_head($catalog[$page]['title']??$titles[$page],$page,$a);
if($data!==null)va_records($data,$page);
if($page==='dashboard') { ?>
<section class="va-welcome"><div><span class="va-eyebrow">YOUR OPERATIONS, IN ONE PLACE</span><h2>Welcome back, <?=va_e($a['username'])?>.</h2><p>View Veegame’s existing users and records from the integrated admin workspace.</p></div><div class="va-welcome-mark"><i class="ri-dashboard-line" aria-hidden="true"></i></div></section>
<div class="va-stats"><?php foreach($counts as $key=>$value) { ?><a class="card va-stat" href="index.php?page=<?=va_e($key)?>"><span class="va-stat-icon"><i class="<?=va_e($catalog[$key]['icon'])?>"></i></span><span class="va-stat-value"><?=$value===null?'—':number_format((int)$value)?></span><span><?=va_e($catalog[$key]['title'])?></span><small><?=$value===null?'Table unavailable':'Existing database records'?></small></a><?php } ?></div>
<div class="va-two-col"><section class="card va-panel"><h2>Operational status</h2><div class="va-detail"><span>Admin login &amp; audit</span><span class="badge bg-label-success">Connected</span></div><div class="va-detail"><span>User management</span><span><?=va_e($checks['Admin user editing'])?></span></div><div class="va-detail"><span>WinGo state</span><strong><?=va_e($checks['WinGo migration state'])?></strong></div><div class="va-detail"><span>Financial actions</span><span class="badge bg-label-warning">Not enabled</span></div><a class="btn btn-outline-primary" href="index.php?page=checks">View integration checks <i class="ri-arrow-right-line"></i></a></section><section class="card va-panel"><h2>What is connected?</h2><p>Admin authentication, user profiles, wallet records, deposit and withdrawal lists, new-engine WinGo records, schema diagnostics and audit history.</p><p><strong>Full operational parity is not complete.</strong> Financial approvals, payouts, site settings and WinGo activation still require the live compatibility checks. No donor keys or automatic wallet changes are installed.</p><a href="index.php?page=users">Manage users →</a></section></div>
<?php }
if($page==='user') {
    $editable=$a['role']==='owner'&&va_unique('shonu_subjects','id')&&va_available('shonu_subjects',['id','status','codechorkamukala','akshinak']); ?>
<a class="va-back" href="index.php?page=users">← All users</a><div class="va-two-col"><section class="card va-panel"><h2>User #<?=va_e($u['id'])?></h2><?php foreach($u as $key=>$value)echo '<div class="va-detail"><span>'.va_e($catalog['users']['cols'][$key]??$key).'</span><span>'.va_raw($value).'</span></div>';?><a class="btn btn-outline-primary" href="index.php?page=wallets&amp;q=<?=va_e($u['id'])?>">View wallet records</a></section><section class="card va-panel"><h2>Edit profile</h2><?php if(!$editable)va_notice('Profile editing is unavailable for this account or database schema.');else { ?>
<p>Changing account status clears the existing account token. It does not cancel, settle or change any existing bet, withdrawal or wallet balance.</p>
<form method="post" action="action.php" class="va-form" data-confirm="Save this user profile change? Changing status clears the user’s existing account token."><?=va_csrf()?><input type="hidden" name="action" value="user_update"><input type="hidden" name="id" value="<?=va_e($u['id'])?>"><input type="hidden" name="version" value="<?=va_e(va_user_version($u))?>">
<label>Nickname<input class="form-control" name="nickname" maxlength="32" value="<?=va_e($u['codechorkamukala'])?>"></label><label>Account status<select class="form-select" name="status" required><option value="">Choose status</option><option value="1" <?=((string)$u['status']==='1'?'selected':'')?>>Active</option><option value="0" <?=((string)$u['status']==='0'?'selected':'')?>>Blocked</option></select></label><label>Reason<textarea class="form-control" name="reason" minlength="5" maxlength="300" required></textarea></label><label>Your admin password<input type="password" class="form-control" name="current_password" autocomplete="current-password" maxlength="128" required></label><button class="btn btn-primary">Save profile</button></form><?php } ?></section></div>
<?php }
if($page==='checks') { ?>
<?php va_notice('These are read-only checks. This page never converts tables, changes balances, starts cron jobs or activates WinGo. Full admin/payment/game cutover is not complete.'); ?>
<section class="card va-panel"><h2>Live compatibility</h2><?php foreach($checks as $label=>$value)echo '<div class="va-detail"><span>'.va_e($label).'</span><strong>'.va_e($value).'</strong></div>';?></section>
<section class="card va-panel va-spaced"><h2>Database structure report</h2><p>Download a diagnostic file to finish mapping the remaining ShreeWin modules. It contains table, column and index definitions only—no user rows, balances, passwords, tokens or connection credentials.</p><?php if($a['role']==='owner') { ?><form method="post" action="action.php" class="va-form"><?=va_csrf()?><input type="hidden" name="action" value="schema_export"><label>Your admin password<input type="password" class="form-control" name="current_password" autocomplete="current-password" maxlength="128" required></label><button class="btn btn-outline-primary">Download structure report</button></form><?php } ?></section>
<?php }
if($page==='security') { ?><section class="card va-panel va-narrow"><h2>Change admin password</h2><p>Use a unique password of at least 12 characters. Changing it signs out all sessions for this admin account. Customer passwords are not modified.</p><?php if($a['role']==='owner') { ?><form class="va-form" method="post" action="action.php"><?=va_csrf()?><input type="hidden" name="action" value="password_change"><label>Current admin password<input class="form-control" type="password" name="current_password" autocomplete="current-password" maxlength="128" required></label><label>New password<input class="form-control" type="password" name="new_password" autocomplete="new-password" minlength="12" maxlength="128" required></label><label>Confirm new password<input class="form-control" type="password" name="password_confirm" autocomplete="new-password" minlength="12" maxlength="128" required></label><button class="btn btn-primary">Change password &amp; sign out</button></form><?php } else va_notice('Owner permission is required.'); ?></section><?php }
va_end();
