<?php
session_start();
if(empty($_SESSION['unohs'])){header('location: api/login.php?msg=unauthorized');exit;}
include('api/conn.php');
date_default_timezone_set('Asia/Kolkata');
function td_exists($db,$table){$safe=$db->real_escape_string($table);$r=$db->query("SHOW TABLES LIKE '{$safe}'");return $r instanceof mysqli_result&&$r->num_rows>0;}
function td_val($db,$sql){try{$r=$db->query($sql);if(!$r)return 0;$x=$r->fetch_row();return (float)($x[0]??0);}catch(Throwable $e){error_log('[team-dashboard] '.$e->getMessage());return 0;}}
$totalUsers=(int)td_val($conn,'SELECT COUNT(*) FROM shonu_subjects');
$activeUsers=(int)td_val($conn,'SELECT COUNT(*) FROM shonu_subjects WHERE status=1');
$todayUsers=(int)td_val($conn,'SELECT COUNT(*) FROM shonu_subjects WHERE DATE(createdate)=CURDATE()');
$totalWallet=td_exists($conn,'shonu_kaichila')?td_val($conn,'SELECT COALESCE(SUM(motta),0) FROM shonu_kaichila'):0;
$totalDeposit=td_exists($conn,'thevani')?td_val($conn,"SELECT COALESCE(SUM(motta),0) FROM thevani WHERE sthiti='1'"):0;
$todayDeposit=td_exists($conn,'thevani')?td_val($conn,"SELECT COALESCE(SUM(motta),0) FROM thevani WHERE sthiti='1' AND DATE(dinankavannuracisi)=CURDATE()"):0;
$totalWithdraw=td_exists($conn,'hintegedukolli')?td_val($conn,"SELECT COALESCE(SUM(motta),0) FROM hintegedukolli WHERE sthiti='1'"):0;
$totalBet=td_exists($conn,'saas_lottery_bets')?td_val($conn,"SELECT COALESCE(SUM(stake),0) FROM saas_lottery_bets WHERE status<>'cancelled'"):0;
$todayBet=td_exists($conn,'saas_lottery_bets')?td_val($conn,"SELECT COALESCE(SUM(stake),0) FROM saas_lottery_bets WHERE status<>'cancelled' AND DATE(created_at)=CURDATE()"):0;
$legacyBetTables=['bajikattuttate','bajikattuttate_drei','bajikattuttate_funf','bajikattuttate_zehn','bajikattuttate_kemuru','bajikattuttate_kemuru_drei','bajikattuttate_kemuru_funf','bajikattuttate_kemuru_zehn','bajikattuttate_aidudi','bajikattuttate_aidudi_drei','bajikattuttate_aidudi_funf','bajikattuttate_aidudi_zehn','bajikattuttate_trx','bajikattuttate_trx3','bajikattuttate_trx5','bajikattuttate_trx10'];
foreach($legacyBetTables as $bt){if(td_exists($conn,$bt)){$totalBet+=td_val($conn,"SELECT COALESCE(SUM(ketebida),0) FROM `{$bt}`");$todayBet+=td_val($conn,"SELECT COALESCE(SUM(ketebida),0) FROM `{$bt}` WHERE DATE(tiarikala)=CURDATE()");}}
$totalCommission=td_exists($conn,'app_saas_commissions')?td_val($conn,'SELECT COALESCE(SUM(commission_amount),0) FROM app_saas_commissions'):0;
if(td_exists($conn,'vyavahara'))$totalCommission+=td_val($conn,"SELECT COALESCE(SUM(ayoga),0) FROM vyavahara WHERE prakara LIKE 'LVLCOMM%'");
$levels=[];
$columns=['code','code1','code2','code3','code4','code5','code6','code7','code8','code9'];
foreach($columns as $i=>$col){
    $exists=$conn->query("SHOW COLUMNS FROM shonu_subjects LIKE '".$conn->real_escape_string($col)."'");
    $levels[$i+1]=($exists instanceof mysqli_result&&$exists->num_rows>0)?(int)td_val($conn,"SELECT COUNT(*) FROM shonu_subjects WHERE status=1 AND `{$col}` IS NOT NULL AND `{$col}`<>''"):0;
}
$recent=[];$q=$conn->query("SELECT id,mobile,owncode,code,createdate,status FROM shonu_subjects ORDER BY id DESC LIMIT 20");if($q)while($r=$q->fetch_assoc())$recent[]=$r;
?>
<!doctype html><html lang="en" class="light-style layout-navbar-fixed layout-menu-fixed layout-compact" dir="ltr" data-theme="theme-default" data-assets-path="assets/" data-template="vertical-menu-template" data-style="light"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Team Dashboard - Veegame Pro Admin</title>
<link rel="icon" type="image/x-icon" href="assets/img/favicon/favicon.ico?v=20260815-team"><link rel="stylesheet" href="assets/vendor/fonts/remixicon/remixicon.css"><link rel="stylesheet" href="assets/vendor/css/rtl/core.css"><link rel="stylesheet" href="assets/vendor/css/rtl/theme-default.css"><link rel="stylesheet" href="assets/css/demo.css"><link rel="stylesheet" href="assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css"><script src="assets/vendor/js/helpers.js"></script><script src="assets/js/config.js"></script>
<style>.metric{border:0;border-radius:12px;box-shadow:0 2px 10px rgba(0,0,0,.06);height:100%}.metric .v{font-size:1.55rem;font-weight:700}.level-chip{min-width:115px}.table td,.table th{vertical-align:middle}</style></head><body><div class="layout-wrapper layout-content-navbar"><div class="layout-container"><?php require_once('layout-menu.php');?><div class="layout-page"><?php require_once('nav.php');?><div class="content-wrapper"><div class="container-xxl flex-grow-1 container-p-y">
<div class="d-flex justify-content-between align-items-center mb-4"><div><h4 class="mb-1">Team Dashboard</h4><p class="text-muted mb-0">Live SQL totals from users, wallet, recharge, withdrawals and lottery ledgers.</p></div><a href="users.php" class="btn btn-primary"><i class="ri-user-search-line me-1"></i>Manage Users</a></div>
<div class="row g-4 mb-4">
<?php $cards=[['Total Users',$totalUsers,'ri-group-line'],['Active Users',$activeUsers,'ri-user-follow-line'],['Today Registrations',$todayUsers,'ri-user-add-line'],['Wallet Balance','₹'.number_format($totalWallet,2),'ri-wallet-3-line'],['Approved Deposits','₹'.number_format($totalDeposit,2),'ri-bank-card-line'],['Successful Withdrawals','₹'.number_format($totalWithdraw,2),'ri-money-rupee-circle-line'],['Lottery Turnover','₹'.number_format($totalBet,2),'ri-bar-chart-box-line'],['Team Commission','₹'.number_format($totalCommission,2),'ri-percent-line']]; foreach($cards as $c):?><div class="col-xl-3 col-md-6"><div class="card metric"><div class="card-body d-flex justify-content-between"><div><div class="text-muted small text-uppercase"><?=htmlspecialchars($c[0])?></div><div class="v mt-1"><?=htmlspecialchars((string)$c[1])?></div></div><i class="<?=htmlspecialchars($c[2])?> ri-28px text-primary"></i></div></div></div><?php endforeach;?>
</div>
<div class="row g-4 mb-4"><div class="col-lg-5"><div class="card h-100"><div class="card-header"><h5 class="mb-0">Today</h5></div><div class="card-body"><div class="d-flex justify-content-between py-2 border-bottom"><span>Approved Deposit</span><b>₹<?=number_format($todayDeposit,2)?></b></div><div class="d-flex justify-content-between py-2"><span>Lottery Bet</span><b>₹<?=number_format($todayBet,2)?></b></div></div></div></div><div class="col-lg-7"><div class="card h-100"><div class="card-header"><h5 class="mb-0">Active Referral Mapping (Tier 1–10)</h5></div><div class="card-body d-flex flex-wrap gap-2"><?php foreach($levels as $n=>$count):?><div class="border rounded p-3 level-chip"><div class="small text-muted">Tier <?=$n?></div><div class="h5 mb-0"><?=number_format($count)?></div></div><?php endforeach;?></div></div></div></div>
<div class="card"><div class="card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Recent Users</h5><span class="badge bg-label-primary"><?=number_format($totalUsers)?> Users</span></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>UID</th><th>Mobile</th><th>Own Code</th><th>Ref Code</th><th>Registered</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($recent as $u):?><tr><td><?=$u['id']?></td><td><?=htmlspecialchars((string)$u['mobile'])?></td><td><?=htmlspecialchars((string)$u['owncode'])?></td><td><?=htmlspecialchars((string)$u['code'])?></td><td><?=htmlspecialchars((string)$u['createdate'])?></td><td><span class="badge <?=$u['status']==1?'bg-label-success':'bg-label-danger'?>"><?=$u['status']==1?'Active':'Inactive'?></span></td><td><a class="btn btn-sm btn-outline-primary" href="manageteam.php?user=<?=$u['id']?>">View Team</a></td></tr><?php endforeach;?></tbody></table></div></div>
</div><?php require_once('footer.php');?></div></div></div></div><script src="assets/vendor/libs/jquery/jquery.js"></script><script src="assets/vendor/libs/popper/popper.js"></script><script src="assets/vendor/js/bootstrap.js"></script><script src="assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script><script src="assets/vendor/js/menu.js"></script><script src="assets/js/main.js"></script></body></html>
