{
    "data": {
        "dataList": [
            {
                "type": "IM",
                "typeName": "IM",
                "userPhoto": "18",
                "nickName": "MemberGTUUVMEC",
                "betAmount": 50.00,
                "amount": 73.50,
                "winTime": "2026-08-25 17:58:02",
                "showType": 2,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190423flxc.png",
                "entryType": "gameItem",
                "typeId": 15037,
                "vendorCode": "IM",
                "vendorId": 15,
                "gameID": "",
                "gameNameEn": "Soccer",
                "state": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "IM",
                "typeName": "IM",
                "userPhoto": "19",
                "nickName": "MemberEBRBDZPT",
                "betAmount": 50.00,
                "amount": 73.50,
                "winTime": "2026-08-25 17:58:02",
                "showType": 2,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190423flxc.png",
                "entryType": "gameItem",
                "typeId": 15037,
                "vendorCode": "IM",
                "vendorId": 15,
                "gameID": "",
                "gameNameEn": "Soccer",
                "state": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "WM_Video",
                "typeName": "WM_Video",
                "userPhoto": "4",
                "nickName": "MemberGPPWDLKJ",
                "betAmount": 50.00,
                "amount": 100.00,
                "winTime": "2026-08-25 16:37:11",
                "showType": 1,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190646k1ms.png",
                "entryType": "gameItem",
                "typeId": 26001,
                "vendorCode": "WM_Video",
                "vendorId": 26,
                "gameID": "101",
                "gameNameEn": "Baccarat",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "WM_Video",
                "typeName": "WM_Video",
                "userPhoto": "1",
                "nickName": "MemberCHJMZPNI",
                "betAmount": 50.00,
                "amount": 100.00,
                "winTime": "2026-08-25 16:35:28",
                "showType": 1,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190646k1ms.png",
                "entryType": "gameItem",
                "typeId": 26001,
                "vendorCode": "WM_Video",
                "vendorId": 26,
                "gameID": "101",
                "gameNameEn": "Baccarat",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "SEXY_Video",
                "typeName": "SEXY_Video",
                "userPhoto": "8",
                "nickName": "MemberPYUHAFTK",
                "betAmount": 40.00,
                "amount": 80.00,
                "winTime": "2026-08-25 16:32:58",
                "showType": 1,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_202608241906599b1q.png",
                "entryType": "gameItem",
                "typeId": 27013,
                "vendorCode": "SEXY_Video",
                "vendorId": 27,
                "gameID": "MX-LIVE-001",
                "gameNameEn": "Baccarat Classic",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "EVO_Video",
                "typeName": "EVO_Video",
                "userPhoto": "3",
                "nickName": "MemberEBXPWFMJ",
                "betAmount": 50.00,
                "amount": 25.00,
                "winTime": "2026-08-25 16:27:26",
                "showType": 1,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190440plxk.png",
                "entryType": "gameItem",
                "typeId": 16366,
                "vendorCode": "EVO_Video",
                "vendorId": 16,
                "gameID": "puu47n7mic3rfd7y",
                "gameNameEn": "Emperor Dragon Tiger",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "4",
                "nickName": "MemberLNEHFJKD",
                "betAmount": 20.00,
                "amount": 340.00,
                "winTime": "2026-08-25 13:36:38",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "6",
                "nickName": "MemberPWHMILSP",
                "betAmount": 20.00,
                "amount": 180.00,
                "winTime": "2026-08-25 13:36:31",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "16",
                "nickName": "MemberXMGMISFS",
                "betAmount": 20.00,
                "amount": 160.00,
                "winTime": "2026-08-25 13:36:17",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "9",
                "nickName": "MemberHKXZPBKQ",
                "betAmount": 20.00,
                "amount": 360.00,
                "winTime": "2026-08-25 13:36:08",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "17",
                "nickName": "MemberESVFADEI",
                "betAmount": 20.00,
                "amount": 96.00,
                "winTime": "2026-08-25 13:36:02",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "14",
                "nickName": "MemberQMFMSJXK",
                "betAmount": 20.00,
                "amount": 80.00,
                "winTime": "2026-08-25 13:36:00",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "16",
                "nickName": "MemberEFZCGNPE",
                "betAmount": 20.00,
                "amount": 20.00,
                "winTime": "2026-08-25 13:35:59",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "16",
                "nickName": "MemberFATMNOJV",
                "betAmount": 20.00,
                "amount": 960.00,
                "winTime": "2026-08-25 13:35:41",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "8",
                "nickName": "MemberTUXDXPWF",
                "betAmount": 20.00,
                "amount": 40.00,
                "winTime": "2026-08-25 13:35:39",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "12",
                "nickName": "MemberLKFEFRDN",
                "betAmount": 20.00,
                "amount": 40.00,
                "winTime": "2026-08-25 13:35:34",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "4",
                "nickName": "MemberSAWNMZEP",
                "betAmount": 20.00,
                "amount": 24.00,
                "winTime": "2026-08-25 13:35:20",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "11",
                "nickName": "MemberEPJJHIJF",
                "betAmount": 20.00,
                "amount": 48.00,
                "winTime": "2026-08-25 13:35:06",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "14",
                "nickName": "MemberGZHSEIXW",
                "betAmount": 20.00,
                "amount": 64.00,
                "winTime": "2026-08-25 13:35:04",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "1",
                "nickName": "MemberEHIBLOOA",
                "betAmount": 20.00,
                "amount": 160.00,
                "winTime": "2026-08-25 13:34:47",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "7",
                "nickName": "MemberUBIRCMUH",
                "betAmount": 20.00,
                "amount": 288.00,
                "winTime": "2026-08-25 13:34:38",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "1",
                "nickName": "MemberPXCCENGV",
                "betAmount": 20.00,
                "amount": 16.00,
                "winTime": "2026-08-25 13:34:36",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "13",
                "nickName": "MemberFULCQKVA",
                "betAmount": 20.00,
                "amount": 96.00,
                "winTime": "2026-08-25 13:34:24",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "9",
                "nickName": "MemberIOVIZPUF",
                "betAmount": 20.00,
                "amount": 128.00,
                "winTime": "2026-08-25 13:34:21",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "11",
                "nickName": "MemberGRHVQQED",
                "betAmount": 20.00,
                "amount": 160.00,
                "winTime": "2026-08-25 13:34:03",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "18",
                "nickName": "MemberUTURUHZJ",
                "betAmount": 20.00,
                "amount": 32.00,
                "winTime": "2026-08-25 13:34:00",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "18",
                "nickName": "MemberGPJSITVO",
                "betAmount": 20.00,
                "amount": 160.00,
                "winTime": "2026-08-25 13:33:56",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "4",
                "nickName": "MemberUJDZUHJJ",
                "betAmount": 20.00,
                "amount": 64.00,
                "winTime": "2026-08-25 13:33:53",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "3",
                "nickName": "MemberKROKIWMW",
                "betAmount": 20.00,
                "amount": 32.00,
                "winTime": "2026-08-25 13:33:37",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "6",
                "nickName": "MemberUWZQADKJ",
                "betAmount": 20.00,
                "amount": 180.00,
                "winTime": "2026-08-25 13:32:06",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "19",
                "nickName": "MemberORMXMIAA",
                "betAmount": 20.00,
                "amount": 432.00,
                "winTime": "2026-08-25 13:31:55",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "1",
                "nickName": "MemberUYPIDGWX",
                "betAmount": 20.00,
                "amount": 160.00,
                "winTime": "2026-08-25 13:31:50",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "14",
                "nickName": "MemberWWVCALMW",
                "betAmount": 20.00,
                "amount": 32.00,
                "winTime": "2026-08-25 13:31:43",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "2",
                "nickName": "MemberLEJNFPYQ",
                "betAmount": 20.00,
                "amount": 160.00,
                "winTime": "2026-08-25 13:31:40",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "11",
                "nickName": "MemberKFJHJBRG",
                "betAmount": 20.00,
                "amount": 120.00,
                "winTime": "2026-08-25 13:31:35",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "8",
                "nickName": "MemberPSXBYWOJ",
                "betAmount": 20.00,
                "amount": 480.00,
                "winTime": "2026-08-25 13:31:30",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "17",
                "nickName": "MemberZHUPYINZ",
                "betAmount": 20.00,
                "amount": 40.00,
                "winTime": "2026-08-25 13:31:27",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "15",
                "nickName": "MemberSZWSVQGJ",
                "betAmount": 20.00,
                "amount": 288.00,
                "winTime": "2026-08-25 13:31:10",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "1",
                "nickName": "MemberBMCDVYQY",
                "betAmount": 20.00,
                "amount": 64.00,
                "winTime": "2026-08-25 13:31:09",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "6",
                "nickName": "MemberZCUZYRMP",
                "betAmount": 20.00,
                "amount": 40.00,
                "winTime": "2026-08-25 13:31:07",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "17",
                "nickName": "MemberHUKOQSOR",
                "betAmount": 20.00,
                "amount": 120.00,
                "winTime": "2026-08-25 13:30:57",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "11",
                "nickName": "MemberKBMTCJUK",
                "betAmount": 20.00,
                "amount": 96.00,
                "winTime": "2026-08-25 13:30:51",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "19",
                "nickName": "MemberCMCIOURS",
                "betAmount": 20.00,
                "amount": 48.00,
                "winTime": "2026-08-25 13:30:49",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "6",
                "nickName": "MemberAWBGOXOC",
                "betAmount": 20.00,
                "amount": 120.00,
                "winTime": "2026-08-25 13:30:45",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "19",
                "nickName": "MemberRZDNEQQL",
                "betAmount": 20.00,
                "amount": 320.00,
                "winTime": "2026-08-25 13:30:37",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "1",
                "nickName": "MemberXYYCAZDF",
                "betAmount": 20.00,
                "amount": 64.00,
                "winTime": "2026-08-25 13:30:33",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "6",
                "nickName": "MemberMBLAJMRH",
                "betAmount": 20.00,
                "amount": 40.00,
                "winTime": "2026-08-25 13:30:27",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "1",
                "nickName": "MemberKIZKHALC",
                "betAmount": 20.00,
                "amount": 180.00,
                "winTime": "2026-08-25 13:30:05",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "8",
                "nickName": "MemberPXBIMVKM",
                "betAmount": 20.00,
                "amount": 192.00,
                "winTime": "2026-08-25 13:29:36",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18009,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "109",
                "gameNameEn": "Fortune Gems",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "9",
                "nickName": "MemberQOXOFWAO",
                "betAmount": 10.00,
                "amount": 1050.00,
                "winTime": "2026-08-25 13:27:17",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18177,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "51",
                "gameNameEn": "Money Coming",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "15",
                "nickName": "MemberIKPAPKRJ",
                "betAmount": 10.00,
                "amount": 15.00,
                "winTime": "2026-08-25 13:27:09",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18177,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "51",
                "gameNameEn": "Money Coming",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "15",
                "nickName": "MemberBFSFDTJC",
                "betAmount": 10.00,
                "amount": 11.00,
                "winTime": "2026-08-25 13:26:46",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18177,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "51",
                "gameNameEn": "Money Coming",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "8",
                "nickName": "MemberNTUZBGDP",
                "betAmount": 10.00,
                "amount": 11.00,
                "winTime": "2026-08-25 13:26:40",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18177,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "51",
                "gameNameEn": "Money Coming",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "5",
                "nickName": "MemberTVGGFLTB",
                "betAmount": 10.00,
                "amount": 11.00,
                "winTime": "2026-08-25 13:26:33",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18177,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "51",
                "gameNameEn": "Money Coming",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "3",
                "nickName": "MemberEAGSFOYE",
                "betAmount": 10.00,
                "amount": 51.00,
                "winTime": "2026-08-25 13:26:13",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18177,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "51",
                "gameNameEn": "Money Coming",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JILI",
                "typeName": "JILI",
                "userPhoto": "16",
                "nickName": "MemberUFMNGBBL",
                "betAmount": 10.00,
                "amount": 51.00,
                "winTime": "2026-08-25 13:25:14",
                "showType": 4,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190502s1ey.png",
                "entryType": "gameItem",
                "typeId": 18177,
                "vendorCode": "JILI",
                "vendorId": 18,
                "gameID": "51",
                "gameNameEn": "Money Coming",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JDB",
                "typeName": "JDB",
                "userPhoto": "9",
                "nickName": "MemberZRBTSXMP",
                "betAmount": 3.00,
                "amount": 49.00,
                "winTime": "2026-08-25 13:02:15",
                "showType": 5,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190301m4bx.png",
                "entryType": "gameItem",
                "typeId": 6091,
                "vendorCode": "JDB",
                "vendorId": 6,
                "gameID": "7009",
                "gameNameEn": "Spirit Tide Legend",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "JDB",
                "typeName": "JDB",
                "userPhoto": "11",
                "nickName": "MemberTYBJVJTD",
                "betAmount": 3.00,
                "amount": 12.00,
                "winTime": "2026-08-25 13:02:10",
                "showType": 5,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190301m4bx.png",
                "entryType": "gameItem",
                "typeId": 6091,
                "vendorCode": "JDB",
                "vendorId": 6,
                "gameID": "7009",
                "gameNameEn": "Spirit Tide Legend",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "SaBa",
                "typeName": "SaBa",
                "userPhoto": "16",
                "nickName": "MemberUJPGLVSJ",
                "betAmount": 200.00,
                "amount": 454.00,
                "winTime": "2026-08-25 12:58:24",
                "showType": 2,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190414qc54.png",
                "entryType": "gameItem",
                "typeId": 14045,
                "vendorCode": "SaBa",
                "vendorId": 14,
                "gameID": "",
                "gameNameEn": "Basketball",
                "state": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "DG",
                "typeName": "DG",
                "userPhoto": "4",
                "nickName": "MemberXVTVBUPI",
                "betAmount": 200.00,
                "amount": 400.00,
                "winTime": "2026-08-25 11:59:44",
                "showType": 1,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190314ij6a.png",
                "entryType": "gameItem",
                "typeId": 7001,
                "vendorCode": "DG",
                "vendorId": 7,
                "gameID": "1_1",
                "gameNameEn": "Baccarat",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "DG",
                "typeName": "DG",
                "userPhoto": "3",
                "nickName": "MemberXPISJBTD",
                "betAmount": 0.00,
                "amount": 200.00,
                "winTime": "2026-08-25 11:58:28",
                "showType": 1,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190314ij6a.png",
                "entryType": "gameItem",
                "typeId": 7001,
                "vendorCode": "DG",
                "vendorId": 7,
                "gameID": "1_1",
                "gameNameEn": "Baccarat",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "TB_Chess",
                "typeName": "TB_Chess",
                "userPhoto": "19",
                "nickName": "MemberNSQNOMBB",
                "betAmount": 10.00,
                "amount": 11.10,
                "winTime": "2026-08-25 11:51:12",
                "showType": 6,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190607twac.png",
                "entryType": "gameItem",
                "typeId": 23035,
                "vendorCode": "TB_Chess",
                "vendorId": 23,
                "gameID": "800",
                "gameNameEn": "Aviator",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "TURBO",
                "typeName": "TURBO",
                "userPhoto": "11",
                "nickName": "MemberBGRVNTXF",
                "betAmount": 5.00,
                "amount": 35.00,
                "winTime": "2026-08-25 11:48:54",
                "showType": 6,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190943gr6s.png",
                "entryType": "gameItem",
                "typeId": 47031,
                "vendorCode": "TURBO",
                "vendorId": 47,
                "gameID": "ringsofolympus",
                "gameNameEn": "Rings Of Olympus",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "TURBO",
                "typeName": "TURBO",
                "userPhoto": "3",
                "nickName": "MemberWXLJIPFL",
                "betAmount": 5.00,
                "amount": 35.00,
                "winTime": "2026-08-25 11:48:12",
                "showType": 6,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190943gr6s.png",
                "entryType": "gameItem",
                "typeId": 47031,
                "vendorCode": "TURBO",
                "vendorId": 47,
                "gameID": "ringsofolympus",
                "gameNameEn": "Rings Of Olympus",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "TURBO",
                "typeName": "TURBO",
                "userPhoto": "6",
                "nickName": "MemberTBHNVZPT",
                "betAmount": 5.00,
                "amount": 35.00,
                "winTime": "2026-08-25 11:48:07",
                "showType": 6,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190943gr6s.png",
                "entryType": "gameItem",
                "typeId": 47031,
                "vendorCode": "TURBO",
                "vendorId": 47,
                "gameID": "ringsofolympus",
                "gameNameEn": "Rings Of Olympus",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "INOUT",
                "typeName": "INOUT",
                "userPhoto": "13",
                "nickName": "MemberBETFLQOW",
                "betAmount": 2.00,
                "amount": 10.78,
                "winTime": "2026-08-25 11:40:06",
                "showType": 6,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190916fd91.png",
                "entryType": "gameItem",
                "typeId": 45012,
                "vendorCode": "INOUT",
                "vendorId": 45,
                "gameID": "chicken-road-two",
                "gameNameEn": "Chicken Road 2",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "V8Card",
                "typeName": "V8Card",
                "userPhoto": "12",
                "nickName": "MemberCKMTFVZZ",
                "betAmount": 40.00,
                "amount": 79.40,
                "winTime": "2026-08-25 11:33:45",
                "showType": 3,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190547agrs.png",
                "entryType": "gameItem",
                "typeId": 21020,
                "vendorCode": "V8Card",
                "vendorId": 21,
                "gameID": "8210",
                "gameNameEn": "Tai Xiu",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "V8Card",
                "typeName": "V8Card",
                "userPhoto": "17",
                "nickName": "MemberKKGXLRNP",
                "betAmount": 40.00,
                "amount": 79.40,
                "winTime": "2026-08-25 11:33:16",
                "showType": 3,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190547agrs.png",
                "entryType": "gameItem",
                "typeId": 21020,
                "vendorCode": "V8Card",
                "vendorId": 21,
                "gameID": "8210",
                "gameNameEn": "Tai Xiu",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "V8Card",
                "typeName": "V8Card",
                "userPhoto": "8",
                "nickName": "MemberYXZVNJWW",
                "betAmount": 40.00,
                "amount": 79.40,
                "winTime": "2026-08-25 11:32:20",
                "showType": 3,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190547agrs.png",
                "entryType": "gameItem",
                "typeId": 21020,
                "vendorCode": "V8Card",
                "vendorId": 21,
                "gameID": "8210",
                "gameNameEn": "Tai Xiu",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "V8Card",
                "typeName": "V8Card",
                "userPhoto": "18",
                "nickName": "MemberEHSEVRYZ",
                "betAmount": 40.00,
                "amount": 79.40,
                "winTime": "2026-08-25 11:31:52",
                "showType": 3,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190547agrs.png",
                "entryType": "gameItem",
                "typeId": 21020,
                "vendorCode": "V8Card",
                "vendorId": 21,
                "gameID": "8210",
                "gameNameEn": "Tai Xiu",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "V8Card",
                "typeName": "V8Card",
                "userPhoto": "16",
                "nickName": "MemberUPRZXEFY",
                "betAmount": 40.00,
                "amount": 79.40,
                "winTime": "2026-08-25 11:31:23",
                "showType": 3,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190547agrs.png",
                "entryType": "gameItem",
                "typeId": 21020,
                "vendorCode": "V8Card",
                "vendorId": 21,
                "gameID": "8210",
                "gameNameEn": "Tai Xiu",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "V8Card",
                "typeName": "V8Card",
                "userPhoto": "17",
                "nickName": "MemberVTQYIAJW",
                "betAmount": 40.00,
                "amount": 79.40,
                "winTime": "2026-08-25 11:30:53",
                "showType": 3,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190547agrs.png",
                "entryType": "gameItem",
                "typeId": 21020,
                "vendorCode": "V8Card",
                "vendorId": 21,
                "gameID": "8210",
                "gameNameEn": "Tai Xiu",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "V8Card",
                "typeName": "V8Card",
                "userPhoto": "15",
                "nickName": "MemberIGATXDPH",
                "betAmount": 80.00,
                "amount": 158.80,
                "winTime": "2026-08-25 11:30:25",
                "showType": 3,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190547agrs.png",
                "entryType": "gameItem",
                "typeId": 21020,
                "vendorCode": "V8Card",
                "vendorId": 21,
                "gameID": "8210",
                "gameNameEn": "Tai Xiu",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "KoolBet",
                "typeName": "KoolBet",
                "userPhoto": "19",
                "nickName": "MemberVHVRSBDF",
                "betAmount": 20.00,
                "amount": 40.00,
                "winTime": "2026-08-25 11:26:53",
                "showType": 3,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190734v5wq.png",
                "entryType": "gameItem",
                "typeId": 44004,
                "vendorCode": "KoolBet",
                "vendorId": 44,
                "gameID": "104",
                "gameNameEn": "7Up7Down",
                "state": 1,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "CMD",
                "typeName": "CMD",
                "userPhoto": "8",
                "nickName": "MemberCJZJONUR",
                "betAmount": 21.00,
                "amount": 40.32,
                "winTime": "2026-08-25 11:18:57",
                "showType": 2,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190325q7cc.png",
                "entryType": "gameItem",
                "typeId": 8040,
                "vendorCode": "CMD",
                "vendorId": 8,
                "gameID": "",
                "gameNameEn": "Soccer",
                "state": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            },
            {
                "type": "CMD",
                "typeName": "CMD",
                "userPhoto": "6",
                "nickName": "MemberDAUPZVLQ",
                "betAmount": 21.00,
                "amount": 39.90,
                "winTime": "2026-08-25 11:18:57",
                "showType": 2,
                "imgUrl": "https://ossimg.shreewinpay.com/shreewin/vendorlogo/vendorlogo_20260824190325q7cc.png",
                "entryType": "gameItem",
                "typeId": 8040,
                "vendorCode": "CMD",
                "vendorId": 8,
                "gameID": "",
                "gameNameEn": "Soccer",
                "state": 0,
                "isMaintain": 0,
                "isGameSaasMaintain": 0
            }
        ],
        "penarikanList": []
    },
    "code": 0,
    "msg": "Succeed",
    "msgCode": 0,
    "traceId": "",
    "serviceNowTime": "2026-08-26 15:43:23"
}