{
    "data": {
        "typelist": [
            {
                "payID": 13,
                "payTypeID": 0,
                "payName": "UPI-QR",
                "paySysName": "ArUpiPay",
                "payNameUrl": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon_20250715160654uyp8.png",
                "payNameUrl2": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon2_20250715160654w7bl.png",
                "minPrice": 0.0,
                "maxPrice": 0.0,
                "scope": null,
                "typeName": "ArUpi Pay",
                "typeNameCode": 9225,
                "maxRechargeRifts": 0.0000,
                "sort": 2001,
                "vipRechargeRate": 0.0
            },
            {
                "payID": 2,
                "payTypeID": 0,
                "payName": "Innate UPI-QR",
                "paySysName": null,
                "payNameUrl": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon_20250715161734pry4.png",
                "payNameUrl2": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon2_20250715161734gmel.png",
                "minPrice": 0.0,
                "maxPrice": 0.0,
                "scope": null,
                "typeName": "Innate UPI-QR",
                "typeNameCode": 0,
                "maxRechargeRifts": 0.0000,
                "sort": 1000,
                "vipRechargeRate": 0.0
            },
            {
                "payID": 1,
                "payTypeID": 0,
                "payName": "Expert Paytm-QR",
                "paySysName": null,
                "payNameUrl": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon_20250715162302wtty.png",
                "payNameUrl2": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon2_202507151623023nbp.png",
                "minPrice": 0.0,
                "maxPrice": 0.0,
                "scope": null,
                "typeName": "Expert Paytm-QR",
                "typeNameCode": 0,
                "maxRechargeRifts": 0.0000,
                "sort": 98,
                "vipRechargeRate": 0.0
            },
            {
                "payID": 3,
                "payTypeID": 0,
                "payName": "UPI-QR PAY",
                "paySysName": null,
                "payNameUrl": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon_20250715160942lbjd.png",
                "payNameUrl2": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon2_20250715161000iyvw.png",
                "minPrice": 0.0,
                "maxPrice": 0.0,
                "scope": null,
                "typeName": "UPI-QR PAY",
                "typeNameCode": 0,
                "maxRechargeRifts": 0.0000,
                "sort": 96,
                "vipRechargeRate": 0.0
            },
            {
                "payID": 11,
                "payTypeID": 0,
                "payName": "USDT",
                "paySysName": null,
                "payNameUrl": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon_202308142205192wpa.jpg",
                "payNameUrl2": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon2_202308142205196p3u.jpg",
                "minPrice": 0.0,
                "maxPrice": 0.0,
                "scope": null,
                "typeName": "USDT",
                "typeNameCode": 9205,
                "maxRechargeRifts": 0.0200,
                "sort": 21,
                "vipRechargeRate": 0.0
            },
            {
                "payID": 21,
                "payTypeID": 0,
                "payName": "ARPay",
                "paySysName": "ARPay",
                "payNameUrl": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon_20241030000604or92.png",
                "payNameUrl2": "https://ossimg.91admin123admin.com/91club/payNameIcon/payNameIcon2_20241030000604diyp.png",
                "minPrice": 0.0,
                "maxPrice": 0.0,
                "scope": null,
                "typeName": "AR Pay",
                "typeNameCode": 9223,
                "maxRechargeRifts": 0.0200,
                "sort": 3,
                "vipRechargeRate": 0.0
            }
        ]
    },
    "code": 0,
    "msg": "Succeed",
    "msgCode": 0,
    "serviceNowTime": "2026-02-28 07:42:52"
}