<?php
if (!defined('VA_ADMIN')) { http_response_code(404); exit; }
function va_login_head(string $title): void { ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=va_e($title)?> · Veegame Admin</title><link rel="stylesheet" href="assets/vendor/css/rtl/core.css"><link rel="stylesheet" href="assets/vendor/fonts/remixicon/remixicon.css"><link rel="stylesheet" href="assets/login.css"></head><body><main class="master-wrapper"><div class="vip-premium-box"><div class="top-neon-line"></div><div class="brand-zone"><i class="ri-flashlight-fill" aria-hidden="true"></i> VEEGAME ADMIN</div><h1 class="section-title"><?=va_e($title)?></h1>
<?php }
function va_login_field(string $name,string $label,string $type,string $autocomplete): void { ?>
<div class="input-wrapper-block"><label class="custom-label" for="<?=va_e($name)?>"><?=va_e($label)?></label><div class="modern-input-group"><div class="input-icon-zone"><i class="<?=$type==='password'?'ri-lock-password-line':'ri-user-settings-line'?>" aria-hidden="true"></i></div><input class="clean-field" id="<?=va_e($name)?>" name="<?=va_e($name)?>" type="<?=va_e($type)?>" autocomplete="<?=va_e($autocomplete)?>" maxlength="128" required></div></div>
<?php }
function va_login_end(): void { echo '</div></main></body></html>'; }
function va_head(string $title,string $page,array $admin): void {
    $menu=['dashboard'=>['Dashboard','ri-dashboard-line'],'users'=>['Users','ri-team-line'],'wallets'=>['Wallet records','ri-wallet-3-line'],'deposits'=>['Deposits','ri-arrow-left-down-line'],'withdrawals'=>['Withdrawals','ri-arrow-right-up-line'],'bets'=>['WinGo records','ri-gamepad-line'],'ledger'=>['WinGo ledger','ri-file-list-3-line'],'audit'=>['Audit log','ri-shield-check-line'],'checks'=>['Integration checks','ri-links-line'],'security'=>['Admin security','ri-lock-line']]; ?>
<!doctype html><html lang="en" class="light-style" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=va_e($title)?> · Veegame Admin</title><link rel="stylesheet" href="assets/vendor/css/rtl/core.css"><link rel="stylesheet" href="assets/vendor/css/rtl/theme-default.css"><link rel="stylesheet" href="assets/vendor/fonts/remixicon/remixicon.css"><link rel="stylesheet" href="assets/admin.css"><script src="assets/admin.js" defer></script></head><body><div class="va-shell">
<aside class="va-menu" id="admin-menu"><a class="va-brand" href="index.php"><span class="va-logo">V</span><span>Veegame<small>ADMIN CONSOLE</small></span></a><p class="va-menu-label">WORKSPACE</p><nav aria-label="Admin navigation">
<?php foreach($menu as $key=>[$label,$icon]) { ?><a class="va-nav-item <?=($page===$key || ($page==='user'&&$key==='users'))?'active':''?>" href="index.php?page=<?=va_e($key)?>"><i class="<?=va_e($icon)?>" aria-hidden="true"></i><span><?=va_e($label)?></span></a><?php } ?>
</nav><div class="va-menu-bottom"><span class="va-status-dot"></span> Veegame Admin</div></aside>
<div class="va-body"><header class="va-topbar"><button class="va-menu-button" type="button" aria-label="Toggle menu" aria-controls="admin-menu" aria-expanded="false"><i class="ri-menu-line"></i></button><div><span class="va-eyebrow">VEEGAME / ADMIN</span><h1><?=va_e($title)?></h1></div><div class="va-admin"><span class="va-avatar"><?=va_e(strtoupper(substr($admin['username'],0,1)))?></span><span><?=va_e($admin['username'])?><small><?=va_e($admin['role'])?></small></span><form method="post" action="logout.php"><?=va_csrf()?><button class="btn btn-sm btn-outline-secondary" type="submit">Log out</button></form></div></header><main class="va-content">
<?php if(!empty($_SESSION['flash'])) { echo '<div class="alert alert-success">'.va_e($_SESSION['flash']).'</div>';unset($_SESSION['flash']); }
}
function va_end(): void { echo '</main><footer class="va-footer">Veegame Admin · Existing records, unchanged timestamps. No game overrides.</footer></div></div></body></html>'; }
function va_notice(string $message): void { echo '<div class="alert alert-warning va-notice"><i class="ri-information-line" aria-hidden="true"></i><span>'.va_e($message).'</span></div>'; }
function va_raw($value): string { if($value===null)return '<span class="va-muted">NULL</span>';if($value==='')return '<span class="va-muted">(empty)</span>';return va_e($value); }
function va_records(array $d,string $page): void {
    if(!$d['available']) {va_notice('This module needs a compatible '.$d['table'].' table. Nothing has been created or changed. Use Integration checks to export the database structure.');return;}
    if(in_array($page,['wallets','deposits','withdrawals'],true))va_notice('Record view only in this release. Balance editing, deposit approval, refunds and payout are not enabled. Amounts are shown exactly as stored, without rounding.');
    if(in_array($page,['bets','ledger'],true))va_notice('Existing new-engine records only. No betting-state, period, result or wallet changes. Legacy bets are not relabelled as new-engine bets.');
    ?><section class="card"><div class="va-card-heading"><div><h2><?=va_e($d['title'])?></h2><p><?=number_format($d['total'])?> matching records · 25 per page</p></div><form class="va-search" method="get"><input type="hidden" name="page" value="<?=va_e($page)?>"><input class="form-control" aria-label="Search records" name="q" value="<?=va_e($d['q'])?>" maxlength="100" placeholder="Search ID, name or order"><?php if(in_array($page,['users','deposits','withdrawals'],true)) { ?><select name="status" class="form-select" aria-label="Filter status"><option value="">All statuses</option><?php foreach(($page==='users'?['0'=>'Blocked (0)','1'=>'Active (1)']:['0'=>'Pending (0)','1'=>'Completed (1)','2'=>'Rejected (2)','3'=>'Processing (3)']) as $key=>$label)echo '<option value="'.va_e($key).'" '.($d['filter']===(string)$key?'selected':'').'>'.va_e($label).'</option>';?></select><?php } ?><button class="btn btn-primary">Search</button></form></div>
<div class="table-responsive"><table class="table"><thead><tr><?php foreach($d['columns'] as $label)echo '<th>'.va_e($label).'</th>';if($page==='users')echo '<th>Profile</th>';?></tr></thead><tbody>
<?php foreach($d['rows'] as $row) {echo '<tr>';foreach($d['columns'] as $key=>$label) { echo '<td>';if($page==='users'&&$key==='status')echo '<span class="badge '.((string)$row[$key]==='1'?'bg-label-success':'bg-label-secondary').'">'.((string)$row[$key]==='1'?'Active':((string)$row[$key]==='0'?'Blocked':va_e($row[$key]))).'</span>';else echo va_raw($row[$key]);echo '</td>'; }if($page==='users')echo '<td><a class="btn btn-sm btn-outline-primary" href="index.php?page=user&amp;id='.va_e($row['id']).'">Open</a></td>';echo '</tr>'; }
if(!$d['rows'])echo '<tr><td colspan="'.(count($d['columns'])+($page==='users'?1:0)).'" class="va-empty">No records match these filters.</td></tr>'; ?>
</tbody></table></div><div class="va-pagination"><span>Page <?=$d['page']?> of <?=$d['pages']?></span><div><?php foreach(['Previous'=>$d['page']-1,'Next'=>$d['page']+1] as $label=>$p)if($p>=1&&$p<=$d['pages'])echo '<a class="btn btn-sm btn-outline-secondary" href="index.php?'.va_e(http_build_query(['page'=>$page,'q'=>$d['q'],'status'=>$d['filter'],'p'=>$p])).'">'.va_e($label).'</a>';?></div></div></section><?php
}
